# Generated by Django 5.2.5 on 2025-11-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerdietplan",
            name="items",
            field=models.JSONField(default=list),
        ),
        migrations.DeleteModel(
            name="DietItem",
        ),
    ]
