# Generated by Django 5.2.5 on 2025-11-23 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_trainerdietplan_items_delete_dietitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainerdietplan",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
