# Generated by Django 5.2.5 on 2025-10-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberprofile',
            name='barcode_image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
