# Generated by Django 5.2.5 on 2025-11-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0002_alter_memberprofile_barcode_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="temp_members/"),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
