# Generated by Django 5.2.5 on 2025-11-08 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0003_memberprofile_image_memberprofile_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="image",
        ),
        migrations.RemoveField(
            model_name="memberprofile",
            name="image_url",
        ),
    ]
