# Generated by Django 5.2.5 on 2025-11-08 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0004_remove_memberprofile_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="memberprofile",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AddField(
            model_name="memberprofile",
            name="image_url",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
