# Generated by Django 5.2.5 on 2025-11-16 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0005_memberprofile_image_memberprofile_image_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="memberprofile",
            name="is_active",
        ),
    ]
