# Generated by Django 5.2.5 on 2025-11-16 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("members", "0006_remove_memberprofile_is_active"),
    ]

    operations = [
        migrations.AlterField(
            model_name="memberprofile",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
